services:
  - type: web
    name: mafia-bot
    runtime: python
    plan: free
    rootDir: mafia-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
